# Name of the workflow as it appears in GitHub Actions tab
name: Playwright Tests

# Defines when this workflow will run
on:
  # Run workflow on every push to the main branch
  push:
    branches: [ main ]
  
  # Run workflow on every pull request targeting main branch
  pull_request:
    branches: [ main ]

# Global environment variables available to all jobs
# Values are taken from GitHub Repository Variables (Settings → Secrets and variables → Actions → Variables)
env:
    BASE_URL: ${{ vars.BASE_URL }}                     # Base URL of the application under test
    EMAIL: ${{ vars.EMAIL }}                           # Login email used in tests
    PASSWORD: ${{ vars.PASSWORD }}                     # Login password used in tests
    CUSTOMER_ID: ${{ vars.CUSTOMER_ID }}               # Test customer ID
    GENERAL_QUOTATION_TYPE: ${{ vars.GENERAL_QUOTATION_TYPE }} # Quotation type test data
    CUSTOMER_FIRST_NAME: ${{ vars.CUSTOMER_FIRST_NAME }}       # Customer first name test data
    CUSTOMER_LAST_NAME: ${{ vars.CUSTOMER_LAST_NAME }}         # Customer last name test data
    CI: ${{ vars.CI }}                                 # CI flag to indicate running in pipeline

# Define jobs section
jobs:
  # Job name: "test"
  test:
    timeout-minutes: 60          # Maximum time allowed for this job before GitHub cancels it
    environment: test            # Uses GitHub Environment named "test" (optional environment protection)
    runs-on: ubuntu-latest       # The virtual machine OS where the job will run

    # Steps executed sequentially inside the job
    steps:

    # Step 1: Checkout repository code to the runner
    - uses: actions/checkout@v5

    # Step 2: Install Node.js (latest LTS version)
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*

    # Step 3: Install project dependencies using clean install
    # npm ci ensures exact versions from package-lock.json
    - name: Install dependencies
      run: npm ci

    # Step 4: Install Playwright browsers and required OS dependencies
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Step 5: Run Playwright automated tests
    - name: Run Playwright tests
      run: npx playwright test

    # Step 6: Upload Playwright HTML report as an artifact
    # So you can download and view test results from GitHub Actions
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}          # Upload only if workflow was not cancelled
      with:
        name: playwright-report         # Artifact name in GitHub
        path: playwright-report/        # Folder path generated by Playwright
        retention-days: 30              # Keep report for 30 days
